### ISSUE TITLE
Implement quality of life features

### ISSUE THREAD

**Issue by theIDinside** [farre/rrcfg-tools#18]
Setting hardware breakpoints (or watch breakpoints) involves, writing expressions in the debug console to be evaluated. To improve the quality of life when using this extension, a feature for providing a UI to input these commands should be implemented.

For instance; user hits a keyboard shortcut (for the currently non-existing command "watch"), a popup window appears (similar to that of the quick pick one) where the user types in `someVariable.foo` which gets passed off to gdb/rr as a watch variable.

Another (possibly larger) feature in relation to this, would be to add a UI panel that shows currently added hardware breakpoints, something which the cppdbg extension seems incapable to do at first glance.

**Comment by farre** [comment]
Closed by #31
